"""Repository-owned acquisition substrate contracts and persistence."""

from rfi.acquisition.contracts import (
    AcquisitionReceipt,
    CandidateDocument,
    Checkpoint,
    DiscoveryProvenance,
    FailurePoint,
    IntervalAcquisitionFailure,
    IntervalAcquisitionRequest,
    IntervalAcquisitionResult,
    IntervalArtifactEnvelope,
    IntervalCoverage,
    IntervalOutcomeReceipt,
    RetrievalOutcome,
    RetrievalResult,
    SourceProfile,
    TranscriptAcquisitionSelection,
    TranscriptAcquisitionTarget,
    TranscriptEventDisposition,
    TranscriptMetadataObservation,
    TranscriptSelectionMode,
    TranscriptSeed,
    TranscriptTurnObservation,
    RelatedArtifactObservation,
    TranscriptLearningFeedback,
)
from rfi.acquisition.engine import (
    AcquisitionEngine,
    AcquisitionKernel,
    AcquisitionRunResult,
    AdapterAcquisitionTrial,
    AdapterCandidate,
    AdapterFailure,
    AdapterRegistry,
    CandidateIdentity,
    DiscoveryOccurrence,
    DiscoveryPage,
    EngineFailurePoint,
    FailureClass,
    RunStatus,
)
from rfi.acquisition.direct_url import DirectUrlAdapter
from rfi.acquisition.edgar import (
    EdgarAdapter,
    load_edgar_profiles,
    user_agent_from_environment,
    validate_edgar_profile,
)
from rfi.acquisition.fixture_adapters import (
    FixtureCatalogAdapter,
    FixtureFeedAdapter,
    fixture_profiles,
)
from rfi.acquisition.repository import AcquisitionRepository
from rfi.acquisition.interval import IntervalAcquisitionService
from rfi.acquisition.earnings_transcripts import (
    EarningsCallTranscriptAcquisition,
    EarningsTranscriptHttpResponse,
    EarningsTranscriptTransport,
    TranscriptDocumentAssessment,
    TranscriptDocumentStatus,
    UrllibEarningsTranscriptTransport,
    classify_transcript_document,
)
from rfi.acquisition.runtime_config import load_runtime_configuration
from rfi.acquisition.sec_form_10k import SecForm10KAdapter
from rfi.acquisition.sec_form_10q import SecForm10QAdapter
from rfi.acquisition.sec_form_20f import SecForm20FAdapter
from rfi.acquisition.sec_form_6k import SecForm6KAdapter
from rfi.acquisition.sec_form_8k import SecForm8KAdapter
from rfi.acquisition.sec_numbered_form import SecNumberedFormAdapter
from rfi.acquisition.sec_provider import (
    SecFilingMetadata,
    SecHttpResponse,
    SecProviderClient,
    SecResponseTooLarge,
    SecRetrievedDocument,
    SecTransport,
    SecUrllibTransport,
)
from rfi.acquisition.sec_api import (
    SecApiAdapter,
    credential_from_environment,
    load_live_profiles,
    validate_live_profile,
)

__all__ = [
    "AcquisitionReceipt",
    "AcquisitionEngine",
    "AcquisitionKernel",
    "AcquisitionRepository",
    "AcquisitionRunResult",
    "AdapterAcquisitionTrial",
    "AdapterCandidate",
    "AdapterFailure",
    "AdapterRegistry",
    "CandidateDocument",
    "CandidateIdentity",
    "Checkpoint",
    "DiscoveryProvenance",
    "DiscoveryOccurrence",
    "DiscoveryPage",
    "DirectUrlAdapter",
    "EngineFailurePoint",
    "EdgarAdapter",
    "EarningsCallTranscriptAcquisition",
    "EarningsTranscriptHttpResponse",
    "EarningsTranscriptTransport",
    "FailurePoint",
    "IntervalAcquisitionFailure",
    "IntervalAcquisitionRequest",
    "IntervalAcquisitionResult",
    "IntervalAcquisitionService",
    "IntervalArtifactEnvelope",
    "IntervalCoverage",
    "IntervalOutcomeReceipt",
    "FailureClass",
    "FixtureCatalogAdapter",
    "FixtureFeedAdapter",
    "RetrievalOutcome",
    "RetrievalResult",
    "RunStatus",
    "SecApiAdapter",
    "SecFilingMetadata",
    "SecForm10KAdapter",
    "SecForm10QAdapter",
    "SecForm20FAdapter",
    "SecForm6KAdapter",
    "SecForm8KAdapter",
    "SecNumberedFormAdapter",
    "SecHttpResponse",
    "SecProviderClient",
    "SecResponseTooLarge",
    "SecRetrievedDocument",
    "SecTransport",
    "SecUrllibTransport",
    "SourceProfile",
    "TranscriptAcquisitionSelection",
    "TranscriptAcquisitionTarget",
    "TranscriptEventDisposition",
    "TranscriptMetadataObservation",
    "TranscriptDocumentAssessment",
    "TranscriptDocumentStatus",
    "TranscriptSelectionMode",
    "TranscriptSeed",
    "TranscriptTurnObservation",
    "RelatedArtifactObservation",
    "TranscriptLearningFeedback",
    "UrllibEarningsTranscriptTransport",
    "credential_from_environment",
    "classify_transcript_document",
    "fixture_profiles",
    "load_live_profiles",
    "load_edgar_profiles",
    "load_runtime_configuration",
    "user_agent_from_environment",
    "validate_live_profile",
    "validate_edgar_profile",
]
